#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="сеть_библиотек")]
	public partial class выдачиdbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    partial void Insertвыдачи(выдачи instance);
    partial void Updateвыдачи(выдачи instance);
    partial void Deleteвыдачи(выдачи instance);
    #endregion
		
		public выдачиdbDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["сеть_библиотекConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public выдачиdbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public выдачиdbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public выдачиdbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public выдачиdbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<выдачи> выдачи
		{
			get
			{
				return this.GetTable<выдачи>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.выдачи")]
	public partial class выдачи : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_код_выдачи;
		
		private int _код_книги;
		
		private System.DateTime _дата_выдачи;
		
		private System.DateTime _дата_сдачи;
		
		private int _читательский_билет;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_код_выдачиChanging(int value);
    partial void Onid_код_выдачиChanged();
    partial void Onкод_книгиChanging(int value);
    partial void Onкод_книгиChanged();
    partial void Onдата_выдачиChanging(System.DateTime value);
    partial void Onдата_выдачиChanged();
    partial void Onдата_сдачиChanging(System.DateTime value);
    partial void Onдата_сдачиChanged();
    partial void Onчитательский_билетChanging(int value);
    partial void Onчитательский_билетChanged();
    #endregion
		
		public выдачи()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_код_выдачи", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_код_выдачи
		{
			get
			{
				return this._id_код_выдачи;
			}
			set
			{
				if ((this._id_код_выдачи != value))
				{
					this.Onid_код_выдачиChanging(value);
					this.SendPropertyChanging();
					this._id_код_выдачи = value;
					this.SendPropertyChanged("id_код_выдачи");
					this.Onid_код_выдачиChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_код_книги", DbType="Int NOT NULL")]
		public int код_книги
		{
			get
			{
				return this._код_книги;
			}
			set
			{
				if ((this._код_книги != value))
				{
					this.Onкод_книгиChanging(value);
					this.SendPropertyChanging();
					this._код_книги = value;
					this.SendPropertyChanged("код_книги");
					this.Onкод_книгиChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_дата_выдачи", DbType="Date NOT NULL")]
		public System.DateTime дата_выдачи
		{
			get
			{
				return this._дата_выдачи;
			}
			set
			{
				if ((this._дата_выдачи != value))
				{
					this.Onдата_выдачиChanging(value);
					this.SendPropertyChanging();
					this._дата_выдачи = value;
					this.SendPropertyChanged("дата_выдачи");
					this.Onдата_выдачиChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_дата_сдачи", DbType="Date NOT NULL")]
		public System.DateTime дата_сдачи
		{
			get
			{
				return this._дата_сдачи;
			}
			set
			{
				if ((this._дата_сдачи != value))
				{
					this.Onдата_сдачиChanging(value);
					this.SendPropertyChanging();
					this._дата_сдачи = value;
					this.SendPropertyChanged("дата_сдачи");
					this.Onдата_сдачиChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_читательский_билет", DbType="Int NOT NULL")]
		public int читательский_билет
		{
			get
			{
				return this._читательский_билет;
			}
			set
			{
				if ((this._читательский_билет != value))
				{
					this.Onчитательский_билетChanging(value);
					this.SendPropertyChanging();
					this._читательский_билет = value;
					this.SendPropertyChanged("читательский_билет");
					this.Onчитательский_билетChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
