#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="сеть_библиотек")]
	public partial class городdbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    partial void Insertгород(город instance);
    partial void Updateгород(город instance);
    partial void Deleteгород(город instance);
    #endregion
		
		public городdbDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["сеть_библиотекConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public городdbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public городdbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public городdbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public городdbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<город> город
		{
			get
			{
				return this.GetTable<город>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.город")]
	public partial class город : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_город;
		
		private string _город1;
		
		private int _страна;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_городChanging(int value);
    partial void Onid_городChanged();
    partial void Onгород1Changing(string value);
    partial void Onгород1Changed();
    partial void OnстранаChanging(int value);
    partial void OnстранаChanged();
    #endregion
		
		public город()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_город", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_город
		{
			get
			{
				return this._id_город;
			}
			set
			{
				if ((this._id_город != value))
				{
					this.Onid_городChanging(value);
					this.SendPropertyChanging();
					this._id_город = value;
					this.SendPropertyChanged("id_город");
					this.Onid_городChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="город", Storage="_город1", DbType="NChar(100) NOT NULL", CanBeNull=false)]
		public string город1
		{
			get
			{
				return this._город1;
			}
			set
			{
				if ((this._город1 != value))
				{
					this.Onгород1Changing(value);
					this.SendPropertyChanging();
					this._город1 = value;
					this.SendPropertyChanged("город1");
					this.Onгород1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_страна", DbType="Int NOT NULL")]
		public int страна
		{
			get
			{
				return this._страна;
			}
			set
			{
				if ((this._страна != value))
				{
					this.OnстранаChanging(value);
					this.SendPropertyChanging();
					this._страна = value;
					this.SendPropertyChanged("страна");
					this.OnстранаChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
