#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="сеть_библиотек")]
	public partial class книгиdbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    partial void Insertкниги(книги instance);
    partial void Updateкниги(книги instance);
    partial void Deleteкниги(книги instance);
    #endregion
		
		public книгиdbDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["сеть_библиотекConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public книгиdbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public книгиdbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public книгиdbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public книгиdbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<книги> книги
		{
			get
			{
				return this.GetTable<книги>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.книги")]
	public partial class книги : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_код_книги;
		
		private string _название;
		
		private int _код_автора;
		
		private System.DateTime _год_издания;
		
		private string _количество_страниц;
		
		private string _обложка;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_код_книгиChanging(int value);
    partial void Onid_код_книгиChanged();
    partial void OnназваниеChanging(string value);
    partial void OnназваниеChanged();
    partial void Onкод_автораChanging(int value);
    partial void Onкод_автораChanged();
    partial void Onгод_изданияChanging(System.DateTime value);
    partial void Onгод_изданияChanged();
    partial void Onколичество_страницChanging(string value);
    partial void Onколичество_страницChanged();
    partial void OnобложкаChanging(string value);
    partial void OnобложкаChanged();
    #endregion
		
		public книги()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_код_книги", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_код_книги
		{
			get
			{
				return this._id_код_книги;
			}
			set
			{
				if ((this._id_код_книги != value))
				{
					this.Onid_код_книгиChanging(value);
					this.SendPropertyChanging();
					this._id_код_книги = value;
					this.SendPropertyChanged("id_код_книги");
					this.Onid_код_книгиChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_название", DbType="NChar(100) NOT NULL", CanBeNull=false)]
		public string название
		{
			get
			{
				return this._название;
			}
			set
			{
				if ((this._название != value))
				{
					this.OnназваниеChanging(value);
					this.SendPropertyChanging();
					this._название = value;
					this.SendPropertyChanged("название");
					this.OnназваниеChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_код_автора", DbType="Int NOT NULL")]
		public int код_автора
		{
			get
			{
				return this._код_автора;
			}
			set
			{
				if ((this._код_автора != value))
				{
					this.Onкод_автораChanging(value);
					this.SendPropertyChanging();
					this._код_автора = value;
					this.SendPropertyChanged("код_автора");
					this.Onкод_автораChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_год_издания", DbType="Date NOT NULL")]
		public System.DateTime год_издания
		{
			get
			{
				return this._год_издания;
			}
			set
			{
				if ((this._год_издания != value))
				{
					this.Onгод_изданияChanging(value);
					this.SendPropertyChanging();
					this._год_издания = value;
					this.SendPropertyChanged("год_издания");
					this.Onгод_изданияChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_количество_страниц", DbType="NChar(1000) NOT NULL", CanBeNull=false)]
		public string количество_страниц
		{
			get
			{
				return this._количество_страниц;
			}
			set
			{
				if ((this._количество_страниц != value))
				{
					this.Onколичество_страницChanging(value);
					this.SendPropertyChanging();
					this._количество_страниц = value;
					this.SendPropertyChanged("количество_страниц");
					this.Onколичество_страницChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_обложка", DbType="NChar(100) NOT NULL", CanBeNull=false)]
		public string обложка
		{
			get
			{
				return this._обложка;
			}
			set
			{
				if ((this._обложка != value))
				{
					this.OnобложкаChanging(value);
					this.SendPropertyChanging();
					this._обложка = value;
					this.SendPropertyChanged("обложка");
					this.OnобложкаChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
