#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="сеть_библиотек")]
	public partial class странаdbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    partial void Insertстрана(страна instance);
    partial void Updateстрана(страна instance);
    partial void Deleteстрана(страна instance);
    #endregion
		
		public странаdbDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["сеть_библиотекConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public странаdbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public странаdbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public странаdbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public странаdbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<страна> страна
		{
			get
			{
				return this.GetTable<страна>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.страна")]
	public partial class страна : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_страна;
		
		private string _страна1;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_странаChanging(int value);
    partial void Onid_странаChanged();
    partial void Onстрана1Changing(string value);
    partial void Onстрана1Changed();
    #endregion
		
		public страна()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_страна", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_страна
		{
			get
			{
				return this._id_страна;
			}
			set
			{
				if ((this._id_страна != value))
				{
					this.Onid_странаChanging(value);
					this.SendPropertyChanging();
					this._id_страна = value;
					this.SendPropertyChanged("id_страна");
					this.Onid_странаChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="страна", Storage="_страна1", DbType="NChar(30) NOT NULL", CanBeNull=false)]
		public string страна1
		{
			get
			{
				return this._страна1;
			}
			set
			{
				if ((this._страна1 != value))
				{
					this.Onстрана1Changing(value);
					this.SendPropertyChanging();
					this._страна1 = value;
					this.SendPropertyChanged("страна1");
					this.Onстрана1Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
