#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="сеть_библиотек")]
	public partial class читателиdbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    partial void Insertчитатели(читатели instance);
    partial void Updateчитатели(читатели instance);
    partial void Deleteчитатели(читатели instance);
    #endregion
		
		public читателиdbDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["сеть_библиотекConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public читателиdbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public читателиdbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public читателиdbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public читателиdbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<читатели> читатели
		{
			get
			{
				return this.GetTable<читатели>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.читатели")]
	public partial class читатели : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_читательский_билет;
		
		private string _ФИО;
		
		private string _адрес;
		
		private string _телефон;
		
		private int _код_города;
		
		private string _фото;
		
		private System.Nullable<int> _UserId;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_читательский_билетChanging(int value);
    partial void Onid_читательский_билетChanged();
    partial void OnФИОChanging(string value);
    partial void OnФИОChanged();
    partial void OnадресChanging(string value);
    partial void OnадресChanged();
    partial void OnтелефонChanging(string value);
    partial void OnтелефонChanged();
    partial void Onкод_городаChanging(int value);
    partial void Onкод_городаChanged();
    partial void OnфотоChanging(string value);
    partial void OnфотоChanged();
    partial void OnUserIdChanging(System.Nullable<int> value);
    partial void OnUserIdChanged();
    #endregion
		
		public читатели()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_читательский_билет", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_читательский_билет
		{
			get
			{
				return this._id_читательский_билет;
			}
			set
			{
				if ((this._id_читательский_билет != value))
				{
					this.Onid_читательский_билетChanging(value);
					this.SendPropertyChanging();
					this._id_читательский_билет = value;
					this.SendPropertyChanged("id_читательский_билет");
					this.Onid_читательский_билетChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ФИО", DbType="NChar(100) NOT NULL", CanBeNull=false)]
		public string ФИО
		{
			get
			{
				return this._ФИО;
			}
			set
			{
				if ((this._ФИО != value))
				{
					this.OnФИОChanging(value);
					this.SendPropertyChanging();
					this._ФИО = value;
					this.SendPropertyChanged("ФИО");
					this.OnФИОChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_адрес", DbType="NChar(100) NOT NULL", CanBeNull=false)]
		public string адрес
		{
			get
			{
				return this._адрес;
			}
			set
			{
				if ((this._адрес != value))
				{
					this.OnадресChanging(value);
					this.SendPropertyChanging();
					this._адрес = value;
					this.SendPropertyChanged("адрес");
					this.OnадресChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_телефон", DbType="NChar(11) NOT NULL", CanBeNull=false)]
		public string телефон
		{
			get
			{
				return this._телефон;
			}
			set
			{
				if ((this._телефон != value))
				{
					this.OnтелефонChanging(value);
					this.SendPropertyChanging();
					this._телефон = value;
					this.SendPropertyChanged("телефон");
					this.OnтелефонChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_код_города", DbType="Int NOT NULL")]
		public int код_города
		{
			get
			{
				return this._код_города;
			}
			set
			{
				if ((this._код_города != value))
				{
					this.Onкод_городаChanging(value);
					this.SendPropertyChanging();
					this._код_города = value;
					this.SendPropertyChanged("код_города");
					this.Onкод_городаChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_фото", DbType="NChar(1000) NOT NULL", CanBeNull=false)]
		public string фото
		{
			get
			{
				return this._фото;
			}
			set
			{
				if ((this._фото != value))
				{
					this.OnфотоChanging(value);
					this.SendPropertyChanging();
					this._фото = value;
					this.SendPropertyChanged("фото");
					this.OnфотоChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Int")]
		public System.Nullable<int> UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
